name: Deploy React to Hostinger via SSH
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install
        npm install framer-motion --save

    - name: Build React app
      run: npm run build

    - name: Deploy build contents via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "dist/*"
        target: "/home/${{ secrets.SSH_USER }}/domains/mintcream-anteater-452365.hostingersite.com/public_html/"
        strip_components: 1
